### ISSUE TITLE
Bug in crop

### ISSUE THREAD

**Issue by St3fi** [whiskyechobravo/image_process#14]
in image_process.py line 65, left comes in front of top

 `return i.crop((int(t), int(l), int(r), int(b)))`
should be instead
 `return i.crop((int(l), int(t), int(r), int(b)))`

**Comment by Ecno92** [comment]
I've checked the current source code and the implementation is like the following: 

```python
def crop(i, t, l, r, b):
    """Crop image i to the box (l,t)-(r,b).

    t, l, r, b (top, left, right, bottom) must be strings specifying
    either a number or a percentage.
    """
    t, l, r, b = convert_box(i, t, l, r, b)
    return i.crop((int(t), int(l), int(r), int(b)))
```

I can see that the beginning description is not equal to the arguments. However I can not say for sure whether the implementation is still not correct as I'm not using this project for cropping. 

Can someone have a look and tell me if this issue can be closed or whether a change is required?

**Comment by St3fi** [comment]
The error is not within the description, but with the usage of the PIL-library and its own `crop()` function. The `crop()` function from the PIL library requires the arguments in this order: 

`# Here the image "im" is cropped and assigned to new variable im_crop`
`im_crop = im.crop((left, upper, right, lower))`

taken from:
[https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.crop](url)

Thus, in the image_process plugin, the order is incorrect with respect to the edges that are cropped.
If you want to use the plugin, you have to know that left and top are swapped. The code is functional, but does not work as expected.

**Comment by Ecno92** [comment]
@St3fi thanks for the feedback. I've created #22. Have a look and let me know if this one can be merged in.

**Comment by St3fi** [comment]
From the looks of it, it should be fine! Thank you!

Haven't tested it though since image_process didn't work the last time I processed my blog with the updated pelican, so i temporarily disabled it. I will test it soon.

**Comment by Ecno92** [comment]
@St3fi I've merged in the changes. Let me know if you find some issues. There is no rush to do a next release right now.
